// Code generated by "stringer -type=state -linecomment"; DO NOT EDIT.

package kernel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[unknownState-0]
	_ = x[runningState-1]
	_ = x[stoppedState-2]
}

const _state_name = "UnknownRunningStopped"

var _state_index = [...]uint8{0, 7, 14, 21}

func (i state) String() string {
	idx := int(i) - 0
	if idx >= len(_state_index)-1 {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[idx]:_state_index[idx+1]]
}
