// Code generated by "tuple -p subLookup key:string, name:string"; DO NOT EDIT.

package kernel

import "fmt"

// subLookup is a tuple holding 2 values: key string, name string.
type subLookup struct {
	key  string
	name string
}

// NewsubLookup creates a new subLookup tuple with the given values.
func NewsubLookup(key string, name string) subLookup {
	return subLookup{key: key, name: name}
}

// Key returns the first value of the tuple.
func (t subLookup) Key() string {
	return t.key
}

// Name returns the second value of the tuple.
func (t subLookup) Name() string {
	return t.name
}

// Len returns the number of values in the tuple.
func (t subLookup) Len() int {
	return 2
}

// String implements fmt.Stringer.
func (t subLookup) String() string {
	return fmt.Sprintf("(%v, %v)", t.key, t.name)
}
